# Generated by Django 4.1.1 on 2022-10-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_alter_product_under_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kart.kartitem'),
        ),
    ]
