# Generated by Django 4.1.1 on 2022-10-03 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kart', '0004_alter_kart_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='KartItem',
            new_name='CartItem',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Karts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
