# Generated by Django 4.1.1 on 2022-10-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0007_alter_cart_options_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount_to_be_paid',
        ),
    ]
